# Generated by Django 3.2.13 on 2022-09-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CephCluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='集群名称')),
                ('cluster_name', models.CharField(max_length=50, verbose_name='CLUSTER_NAME配置名称')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名称(USER_NAME)')),
                ('disable_choice', models.BooleanField(default=False, help_text='默认false, 如果为true则该ceph配置不启用', verbose_name='禁用选择(DISABLE_CHOICE)')),
                ('pool_names', models.JSONField(default=list, help_text='配置标准：["池名1","池名2" ...]', verbose_name='POOL存储池名称')),
                ('config', models.TextField(default='', verbose_name='ceph集群配置文本')),
                ('config_file', models.CharField(blank=True, editable=False, help_text='点击保存，配置文本会存储到这个文件, 此字段自动填充', max_length=200, verbose_name='配置文件保存路径')),
                ('keyring', models.TextField(verbose_name='ceph集群keyring文本')),
                ('keyring_file', models.CharField(blank=True, editable=False, help_text='点击保存，keyring文本会存储到这个文件, 此字段自动填充', max_length=200, verbose_name='keyring文件保存路径')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('alias', models.CharField(default='default', max_length=16, unique=True, verbose_name='CEPH集群配置别名')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'CEPH集群',
                'verbose_name_plural': 'CEPH集群',
                'ordering': ('id',),
            },
        ),
    ]
