# Generated by Django 3.2.13 on 2023-02-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cephcluster',
            name='alias',
        ),
        migrations.AddField(
            model_name='cephcluster',
            name='priority_stored_value',
            field=models.IntegerField(blank=True, default=None, help_text='根据排序，选择最大值为默认的存储池,请合理填入（-2147483648 到 2147483647）', null=True, verbose_name='优先值'),
        ),
        migrations.AlterField(
            model_name='cephcluster',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='存储池名称'),
        ),
    ]
