# Generated by Django 3.2.13 on 2023-02-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceph', '0002_auto_20230217_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cephcluster',
            name='priority_stored_value',
            field=models.IntegerField(default=0, help_text='根据排序，选择最小值为默认的存储池,请合理填入（-2147483648 到 2147483647）', verbose_name='优先值'),
        ),
    ]
