# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 06:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnusagedescription',
            name='content',
            field=ckeditor.fields.RichTextField(default='', verbose_name='说明内容'),
        ),
    ]
