# Generated by Django 2.2.8 on 2019-12-22 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vpn', '0002_auto_20190107_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNAuth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='', max_length=20, verbose_name='VPN口令')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_auth', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'VPN口令',
                'verbose_name_plural': 'VPN口令',
                'db_table': 'vpn_authentication',
                'ordering': ('-id',),
            },
        ),
    ]
