# Generated by Django 2.2.1 on 2019-05-31 00:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    
    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254, verbose_name='发送者')),
                ('receiver', models.EmailField(max_length=254, verbose_name='接收者')),
                ('message', models.CharField(max_length=1000, verbose_name='邮件内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('company', models.CharField(default='', max_length=255, verbose_name='公司/单位')),
                ('telephone', models.CharField(default='', max_length=11, verbose_name='电话')),
                ('third_app', models.SmallIntegerField(choices=[(0, 'Local user.'), (1, '科技云通行证')], default=0, verbose_name='第三方应用登录')),
                ('secret_key', models.CharField(blank=True, default='', max_length=20, verbose_name='个人密钥')),
                ('last_active', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='最后活跃日期')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthKey',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='access_key')),
                ('secret_key', models.CharField(default='', max_length=50, verbose_name='secret_key')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '停用')], default=True, help_text='正常或者停用', verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.IntegerField(choices=[(0, '可读可写'), (1, '只读')], default=0, verbose_name='读写权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '访问密钥',
                'verbose_name_plural': '访问密钥',
                'ordering': ['-create_time'],
            },
        ),
    ]
