# Generated by Django 2.2.2 on 2019-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0009_auto_20190515_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.SmallIntegerField(choices=[(0, '普通用户'), (1, '超级用户'), (2, '第三方APP超级用户')], default=0, verbose_name='角色权限'),
        ),
    ]
