# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=254, verbose_name='发送者')),
                ('receiver', models.EmailField(max_length=254, verbose_name='接收者')),
                ('message', models.CharField(max_length=1000, verbose_name='邮件内容')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
            },
        ),
    ]
