# Generated by Django 2.2.2 on 2019-09-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
