# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(default='', max_length=255, verbose_name='公司/单位'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='', max_length=11, verbose_name='电话'),
        ),
    ]
