# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181220_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthKey',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='access_key')),
                ('secret_key', models.CharField(default='', max_length=50, verbose_name='secret_key')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '停用')], default=True, help_text='正常或者停用', verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.IntegerField(default=0, verbose_name='读写权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '访问密钥',
                'verbose_name_plural': '访问密钥',
            },
        ),
    ]
