# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190214_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authkey',
            options={'ordering': ['-create_time'], 'verbose_name': '访问密钥', 'verbose_name_plural': '访问密钥'},
        ),
    ]
