# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_third_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(default='', max_length=20, verbose_name='密钥'),
        ),
    ]
