# Generated by Django 2.2.1 on 2019-05-15 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='最后活跃日期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='个人密钥'),
        ),
    ]
