# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_squashed_0012_auto_20190128_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(db_index=True, max_length=63, unique=True, verbose_name='bucket名称'),
        ),
    ]
