# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'verbose_name': '存储桶', 'verbose_name_plural': '存储桶'},
        ),
    ]
