# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_auto_20180926_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='access_permission',
            field=models.SmallIntegerField(choices=[(1, '私有'), (2, '公有')], default=2, verbose_name='访问权限'),
        ),
    ]
