# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_bucket_access_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='soft_delete',
            field=models.BooleanField(choices=[(True, '删除'), (False, '正常')], default=False, verbose_name='软删除'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='access_permission',
            field=models.SmallIntegerField(choices=[(1, '公有'), (2, '私有')], default=2, verbose_name='访问权限'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='bucket名称'),
        ),
    ]
