# Generated by Django 2.2.2 on 2019-09-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_bucket_stats_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='ftp_enable',
            field=models.BooleanField(default=False, verbose_name='FTP可用状态'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='ftp_password',
            field=models.CharField(blank=True, max_length=20, verbose_name='FTP访问密码'),
        ),
    ]
