# Generated by Django 2.2.5 on 2019-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_auto_20190903_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagedescription',
            name='desc_for',
            field=models.SmallIntegerField(choices=[(0, 'API说明'), (1, 'FTP说明')], default=0, verbose_name='关于什么的说明'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='ftp_ro_password',
            field=models.CharField(blank=True, max_length=20, verbose_name='FTP只读访问密码'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='collection_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='存储桶对应的表名'),
        ),
    ]
