# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_auto_20181019_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='collection_name',
            field=models.CharField(default='<function uuid4 at 0x7fd5f622e488>', editable=False, max_length=50, verbose_name='存储桶对应的集合表名'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(db_index=True, max_length=63, verbose_name='bucket名称'),
        ),
    ]
