# Generated by Django 2.2.5 on 2019-12-12 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_auto_20191028_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiusagedescription',
            options={'verbose_name': '使用说明', 'verbose_name_plural': '使用说明'},
        ),
    ]
