# Generated by Django 2.2.8 on 2019-12-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_auto_20191028_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='access_permission',
            field=models.SmallIntegerField(choices=[(1, '公有'), (2, '私有'), (3, '公有（可读写）')], default=2, verbose_name='访问权限'),
        ),
    ]
