# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 09:15
from __future__ import unicode_literals

import buckets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0005_auto_20181116_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='collection_name',
            field=models.CharField(default=buckets.models.get_uuid1_hex_string, editable=False, max_length=50, verbose_name='存储桶对应的集合表名'),
        ),
    ]
