# Generated by Django 2.2.8 on 2019-12-22 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '0006_auto_20191218_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='soft_delete',
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_id', models.BigIntegerField(verbose_name='bucket id')),
                ('archive_time', models.DateTimeField(auto_now_add=True, verbose_name='删除归档时间')),
                ('name', models.CharField(db_index=True, max_length=63, unique=True, verbose_name='bucket名称')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('table_name', models.CharField(blank=True, default='', max_length=50, verbose_name='存储桶对应的表名')),
                ('access_permission', models.SmallIntegerField(choices=[(1, '公有'), (2, '私有'), (3, '公有（可读写）')], default=2, verbose_name='访问权限')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('objs_count', models.IntegerField(default=0, verbose_name='对象数量')),
                ('size', models.BigIntegerField(default=0, verbose_name='桶大小')),
                ('stats_time', models.DateTimeField(verbose_name='统计时间')),
                ('ftp_enable', models.BooleanField(default=False, verbose_name='FTP可用状态')),
                ('ftp_password', models.CharField(blank=True, max_length=20, verbose_name='FTP访问密码')),
                ('ftp_ro_password', models.CharField(blank=True, max_length=20, verbose_name='FTP只读访问密码')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '存储桶归档',
                'verbose_name_plural': '存储桶归档',
                'ordering': ['-id'],
            },
        ),
    ]
