# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 03:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '0006_auto_20181116_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketLimitConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField(default=2, verbose_name='可拥有存储桶上限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlimit', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '桶上限配置',
                'verbose_name_plural': '桶上限配置',
            },
        ),
    ]
