# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_bucketlimitconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
