# Generated by Django 2.2.8 on 2019-12-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_auto_20191222_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='name',
            field=models.CharField(db_index=True, max_length=63, verbose_name='bucket名称'),
        ),
    ]
