# Generated by Django 2.2.8 on 2020-01-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20191212_1116'),
        ('buckets', '0008_auto_20191223_1342'),
    ]

    operations = [
    ]
