# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0008_bucket_modified_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='objs_count',
            field=models.IntegerField(default=0, verbose_name='对象数量'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='size',
            field=models.BigIntegerField(default=0, verbose_name='桶大小'),
        ),
    ]
