# Generated by Django 2.2.8 on 2020-01-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_merge_20200109_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='pool_name',
            field=models.CharField(default='', max_length=32, verbose_name='PoolName'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='pool_name',
            field=models.CharField(default='', max_length=32, verbose_name='PoolName'),
        ),
    ]
