# Generated by Django 2.2.8 on 2020-02-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_auto_20200116_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['-id'], 'verbose_name': '存储桶', 'verbose_name_plural': '存储桶'},
        ),
        migrations.AddField(
            model_name='bucket',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
    ]
