# Generated by Django 2.2.14 on 2020-12-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0013_auto_20200902_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='lock',
            field=models.SmallIntegerField(choices=[(0, '正常读写'), (1, '锁定写'), (2, '锁定读写')], default=0, help_text='锁定存储桶，控制存储桶的读写。', verbose_name='读写锁'),
        ),
    ]
