# Generated by Django 3.2.5 on 2021-08-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0015_buckettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='ftp_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='FTP访问密码'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='ftp_ro_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='FTP只读访问密码'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='ftp_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='FTP访问密码'),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='ftp_ro_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='FTP只读访问密码'),
        ),
    ]
