# Generated by Django 3.2.4 on 2021-10-15 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0016_auto_20210825_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.URLField(help_text='http(s)://exemple.com', max_length=255, verbose_name='备份点服务地址')),
                ('bucket_token', models.CharField(max_length=32, verbose_name='备份点bucket读写token')),
                ('bucket_name', models.CharField(max_length=63, verbose_name='备份点bucket名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('start', '开启同步'), ('stop', '暂停同步'), ('deleted', '删除')], default='stop', max_length=16, verbose_name='状态')),
                ('backup_num', models.SmallIntegerField(choices=[(1, '1'), (2, '2')], default=1, verbose_name='备份点编号')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_buckets', to='buckets.bucket', verbose_name='存储桶')),
            ],
            options={
                'verbose_name': '存储桶备份点',
                'verbose_name_plural': '存储桶备份点',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='backupbucket',
            constraint=models.UniqueConstraint(fields=('bucket', 'backup_num'), name='unique_bucket_backup_num'),
        ),
    ]
