# Generated by Django 3.2.4 on 2021-10-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0017_auto_20211015_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='ceph_using',
            field=models.CharField(default='default', max_length=16, verbose_name='CEPH集群配置别名'),
        ),
        migrations.AddField(
            model_name='bucket',
            name='ceph_using',
            field=models.CharField(default='default', max_length=16, verbose_name='CEPH集群配置别名'),
        ),
    ]
