# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 02:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvcloudVM',
            fields=[
                ('vm_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='虚拟机uuid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('vm_image', models.CharField(max_length=200, verbose_name='镜像')),
                ('vm_cpu', models.CharField(max_length=50, verbose_name='CPU数量')),
                ('vm_mem', models.CharField(max_length=50, verbose_name='内存容量')),
                ('vm_ip', models.GenericIPAddressField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('group_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
