# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 06:42
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):



    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvcloudVM',
            fields=[
                ('vm_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, verbose_name='虚拟机uuid')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('vm_image', models.CharField(max_length=200, verbose_name='镜像')),
                ('vm_cpu', models.CharField(max_length=50, verbose_name='CPU数量')),
                ('vm_mem', models.CharField(max_length=50, verbose_name='内存容量')),
                ('vm_ip', models.GenericIPAddressField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('group_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '虚拟机列表',
                'verbose_name_plural': '虚拟机列表',
            },
        ),
        migrations.CreateModel(
            name='VMLimit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField(default=1, verbose_name='限制数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '虚拟机限制',
                'verbose_name_plural': '虚拟机限制',
            },
        ),
        migrations.CreateModel(
            name='VMConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField(verbose_name='cpu数量')),
                ('mem', models.IntegerField(verbose_name='内存容量')),
                ('time', models.IntegerField(verbose_name='使用期限（月）')),
            ],
            options={
                'verbose_name': '虚拟机配置下拉菜单',
                'verbose_name_plural': '虚拟机配置下拉菜单',
            },
        ),
        migrations.CreateModel(
            name='APIAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150, verbose_name='api_url')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('flag', models.BooleanField(verbose_name='是否当前使用')),
                ('group_id', models.IntegerField(default=1)),
                ('pool_id', models.IntegerField(default=1)),
                ('vlan_id', models.IntegerField(default=3)),
                ('description', models.CharField(default='', max_length=50, verbose_name='描述')),
                ('limit', models.IntegerField(default=1, verbose_name='虚拟机限制')),
            ],
            options={
                'verbose_name': 'api调用配置表',
                'verbose_name_plural': 'api调用配置表',
            },
        ),
        migrations.AddField(
            model_name='vmlimit',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evcloud.APIAuth', verbose_name='api_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evcloudvm',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evcloud.APIAuth', verbose_name='api_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vmlimit',
            name='limit',
            field=models.IntegerField(verbose_name='限制数量'),
        ),
        migrations.CreateModel(
            name='VMUsageDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='虚拟云主机使用说明', max_length=255, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='说明内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '虚拟云主机使用说明',
                'verbose_name_plural': '虚拟云主机使用说明',
            },
        ),
        migrations.AlterModelOptions(
            name='evcloudvm',
            options={'ordering': ['-created_time'], 'verbose_name': '虚拟机列表', 'verbose_name_plural': '虚拟机列表'},
        ),
    ]
