# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0001_squashed_0017_auto_20190128_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauth',
            name='group_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apiauth',
            name='limit',
            field=models.IntegerField(verbose_name='虚拟机限制'),
        ),
        migrations.AlterField(
            model_name='apiauth',
            name='pool_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apiauth',
            name='vlan_id',
            field=models.IntegerField(),
        ),
    ]
