# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 03:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evcloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMLimit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('limit', models.IntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
