# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0002_vmlimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpu', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
            options={
                'verbose_name': '虚拟机配置可选列表',
                'verbose_name_plural': '虚拟机配置可选列表',
            },
        ),
        migrations.AlterModelOptions(
            name='vmlimit',
            options={'verbose_name': '虚拟机限制', 'verbose_name_plural': '虚拟机限制'},
        ),
    ]
