# Generated by Django 2.2.2 on 2019-08-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0002_auto_20190128_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcloudvm',
            name='vm_image_name',
            field=models.CharField(default='', max_length=50, verbose_name='镜像名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evcloudvm',
            name='vm_image',
            field=models.CharField(max_length=200, verbose_name='镜像id'),
        ),
    ]
