# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0003_auto_20181201_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150, verbose_name='api_url')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=50, verbose_name='密码')),
                ('flag', models.BooleanField()),
            ],
            options={
                'verbose_name': 'api调用配置表',
                'verbose_name_plural': 'api调用配置表',
            },
        ),
        migrations.AlterField(
            model_name='vmconfig',
            name='cpu',
            field=models.IntegerField(verbose_name='cpu数量'),
        ),
        migrations.AlterField(
            model_name='vmconfig',
            name='mem',
            field=models.IntegerField(verbose_name='内存容量'),
        ),
        migrations.AlterField(
            model_name='vmconfig',
            name='time',
            field=models.IntegerField(verbose_name='使用期限（月）'),
        ),
        migrations.AlterField(
            model_name='vmlimit',
            name='limit',
            field=models.IntegerField(default=3, verbose_name='限制数量'),
        ),
    ]
