# Generated by Django 2.2.2 on 2019-08-27 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0003_auto_20190827_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcloudvm',
            name='vm_image_name',
        ),
    ]
