# Generated by Django 2.2.2 on 2019-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0004_remove_evcloudvm_vm_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcloudvm',
            name='vm_image_name',
            field=models.CharField(default='Centos_7 64bit', max_length=50, verbose_name='镜像名'),
            preserve_default=False,
        ),
    ]
