# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0004_auto_20181201_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evcloudvm',
            options={'verbose_name': '虚拟机列表', 'verbose_name_plural': '虚拟机列表'},
        ),
        migrations.AlterModelOptions(
            name='vmconfig',
            options={'verbose_name': '虚拟机配置下拉菜单', 'verbose_name_plural': '虚拟机配置下拉菜单'},
        ),
        migrations.AddField(
            model_name='apiauth',
            name='group_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiauth',
            name='net_type_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiauth',
            name='pool_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiauth',
            name='vlan_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiauth',
            name='flag',
            field=models.BooleanField(verbose_name='是否当前使用'),
        ),
    ]
