# Generated by Django 2.2.5 on 2019-10-28 03:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evcloud', '0005_evcloudvm_vm_image_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vmlimit',
            unique_together={('api', 'user')},
        ),
    ]
