# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0005_auto_20181204_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmlimit',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='限制数量'),
        ),
    ]
