# Generated by Django 2.2.5 on 2019-12-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0006_auto_20191028_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauth',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='api_url'),
        ),
    ]
