# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0007_remove_apiauth_net_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiauth',
            name='description',
            field=models.CharField(max_length=50, null=True, verbose_name='描述'),
        ),
    ]
