# Generated by Django 2.2.5 on 2019-12-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0007_auto_20191212_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauth',
            name='pool_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
