# Generated by Django 2.2.5 on 2019-12-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0008_auto_20191212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiauth',
            name='center_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
