# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0008_apiauth_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmlimit',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evcloud.APIAuth', verbose_name='api_id'),
            preserve_default=False,
        ),
    ]
