# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0010_evcloudvm_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiauth',
            name='limit',
            field=models.IntegerField(default=1, verbose_name='虚拟机限制'),
            preserve_default=False,
        ),
    ]
