# Generated by Django 2.2.5 on 2019-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0010_remove_apiauth_pool_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauth',
            name='center_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apiauth',
            name='url',
            field=models.CharField(max_length=150, verbose_name='api_url'),
        ),
    ]
