# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evcloud', '0011_apiauth_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmlimit',
            name='limit',
            field=models.IntegerField(verbose_name='限制数量'),
        ),
    ]
